/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean anyModZero(int [ ] array, int e) {
        System.out.println("inside search");
        if (array == null) return false;
  
        for (int elt : array) {
          if ((elt % e)==0) return true;
        }
        return false;
      }
      
}
